# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import node_info_pb2 as node__info__pb2


class NodeInfoStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NodeJoin = channel.unary_unary(
                '/kiss.NodeInfo/NodeJoin',
                request_serializer=node__info__pb2.JoinRequest.SerializeToString,
                response_deserializer=node__info__pb2.JoinReply.FromString,
                )


class NodeInfoServicer(object):
    """The greeting service definition.
    """

    def NodeJoin(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NodeJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeJoin,
                    request_deserializer=node__info__pb2.JoinRequest.FromString,
                    response_serializer=node__info__pb2.JoinReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kiss.NodeInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeInfo(object):
    """The greeting service definition.
    """

    @staticmethod
    def NodeJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kiss.NodeInfo/NodeJoin',
            node__info__pb2.JoinRequest.SerializeToString,
            node__info__pb2.JoinReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
