# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_info.proto',
  package='kiss',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fnode_info.proto\x12\x04kiss\"-\n\x0bJoinRequest\x12\x13\n\x06nodeIp\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_nodeIp\"+\n\tJoinReply\x12\x13\n\x06isJoin\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\t\n\x07_isJoin2<\n\x08NodeInfo\x12\x30\n\x08NodeJoin\x12\x11.kiss.JoinRequest\x1a\x0f.kiss.JoinReply\"\x00\x62\x06proto3'
)




_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='kiss.JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeIp', full_name='kiss.JoinRequest.nodeIp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_nodeIp', full_name='kiss.JoinRequest._nodeIp',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=25,
  serialized_end=70,
)


_JOINREPLY = _descriptor.Descriptor(
  name='JoinReply',
  full_name='kiss.JoinReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isJoin', full_name='kiss.JoinReply.isJoin', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_isJoin', full_name='kiss.JoinReply._isJoin',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=72,
  serialized_end=115,
)

_JOINREQUEST.oneofs_by_name['_nodeIp'].fields.append(
  _JOINREQUEST.fields_by_name['nodeIp'])
_JOINREQUEST.fields_by_name['nodeIp'].containing_oneof = _JOINREQUEST.oneofs_by_name['_nodeIp']
_JOINREPLY.oneofs_by_name['_isJoin'].fields.append(
  _JOINREPLY.fields_by_name['isJoin'])
_JOINREPLY.fields_by_name['isJoin'].containing_oneof = _JOINREPLY.oneofs_by_name['_isJoin']
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinReply'] = _JOINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'node_info_pb2'
  # @@protoc_insertion_point(class_scope:kiss.JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinReply = _reflection.GeneratedProtocolMessageType('JoinReply', (_message.Message,), {
  'DESCRIPTOR' : _JOINREPLY,
  '__module__' : 'node_info_pb2'
  # @@protoc_insertion_point(class_scope:kiss.JoinReply)
  })
_sym_db.RegisterMessage(JoinReply)



_NODEINFO = _descriptor.ServiceDescriptor(
  name='NodeInfo',
  full_name='kiss.NodeInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='NodeJoin',
    full_name='kiss.NodeInfo.NodeJoin',
    index=0,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODEINFO)

DESCRIPTOR.services_by_name['NodeInfo'] = _NODEINFO

# @@protoc_insertion_point(module_scope)
